/*
Ripped from https://docs.bazel.build/versions/master/skylark/concepts.html

1) Loading phase.
First, we load and evaluate all extensions and all BUILD files that are needed
for the build. The execution of the BUILD files simply instantiates rules (each
time a rule is called, it gets added to a graph). This is where macros are
evaluated.

2) Analysis phase.
The code of the rules is executed (their implementation function), and actions
are instantiated. An action describes how to generate a set of outputs from a
set of inputs, e.g. "run gcc on hello.c and get hello.o". It is important to
note that we have to list explicitly which files will be generated before
executing the actual commands. In other words, the analysis phase takes the
graph generated by the loading phase and generates an action graph.

3) Execution phase.
Actions are executed, when at least one of their outputs is required. If a file
is missing or if a command fails to generate one output, the build fails. Tests
are also run during this phase.
*/
